In [20]:
import numpy as np 
import pandas as pd 
import sklearn
import warnings

In [21]:
def warn(*args, **kwargs):
    pass 
warnings.warn = warn

In [22]:
# file csv yang akan diproses
file_4 = 'starter.csv'

# panggil filenya dan masukan ke dalam variabel data_n
data_4 = pd.read_csv(file_4)

# lihat dimensi semua filenya 
print('(n_baris, n_kolom)')
print('data_2 :\n', data_4.shape)

(n_baris, n_kolom)
data_2 :
 (10, 8)

### DATA_1

In [23]:
data_4

,Voltase,Arus,Umur,Switch,Arang,Lahar,Dinamo,Hasil
0,12,3,<1tahun,Bagus,Tebal,Bagus,Bagus,Tidak ada yang diganti
1,12,3,<1tahun,Bagus,Tebal,Bagus,Rusak,Ganti dinamo starter
2,12,3,<1tahun,Bagus,Tebal,Meleleh,Bagus,Ganti lahar dinamo
3,12,3,<1tahun,Bagus,Tipis,Bagus,Bagus,Ganti arang starter
4,12,3,<1tahun,Rusak,Tebal,Bagus,Bagus,Ganti switch starter
5,12,3,>1tahun,Bagus,Tebal,Bagus,Bagus,Ganti aki
6,12,<3,<1tahun,Bagus,Tebal,Bagus,Bagus,Ganti aki
7,<12,3,<1tahun,Bagus,Tebal,Bagus,Bagus,Ganti aki
8,12,3,>1tahun,Bagus,Tebal,Bagus,Bagus,Tidak ada yang diganti
9,12,3,<1tahun,Rusak,Tipis,Bagus,Bagus,Ganti switch starter kemudian arang starter

In [24]:
# kita lihat nilai - nilai unique dalam datanya
data_4['Hasil'].unique()

array(['Tidak ada yang diganti', 'Ganti dinamo starter',
       'Ganti lahar dinamo', 'Ganti arang starter',
       'Ganti switch starter', 'Ganti aki',
       'Ganti switch starter kemudian arang starter'], dtype=object)

In [25]:
# kita hitung berapa jumlah kelas di kolom 'Hasil' tersbeut 
data_4['Hasil'].value_counts()

Ganti aki                                      3
Tidak ada yang diganti                         2
Ganti lahar dinamo                             1
Ganti arang starter                            1
Ganti switch starter kemudian arang starter    1
Ganti switch starter                           1
Ganti dinamo starter                           1
Name: Hasil, dtype: int64

Terlihat bahwa jumlah class yang tersebar di dalam kolom Hasil itu bersifat tidak merata. artinya class 'Tidak ada yang diganti' memiliki jumlah paling banyak (mendominasi) dibandingkan dengan class yang lain seperti 'Oli diganti', 'tali gas diganti' dll. sehingga, agar menghasilkan model yang baik, maka jumlah class ini harus disama-ratakan (balancing) agar distribusi nilainya merata. sehingga akan semakin baik dalam menyimpulkan/memprediksi data

### Random oversampling

In [26]:
'''
import library imblearn. karena data kita mengalami imbalance class
di mana imbalance class ini merupakan kondisi ketidakseimabagan jumlah 
class yang terdistribusi di dalam suatu field/kolom, sehingga menyebabkan
sistem tersebut mengalami kesulitasn dalam training dan validasi.
'''
from imblearn.over_sampling import RandomOverSampler
from collections import Counter

# kita pecah datasetnya menjadi dua bagian yaitu variabel features dan variabel target
# X ==> berisi variabel-variabel features
X = data_4.iloc[:, :-1]

# Y ==> berisi sebuah variabel target
y = data_4.iloc[:, -1]

# mulai sampling
ros = RandomOverSampler(random_state=0, )
X_resampled, y_resampled = ros.fit_sample(X, y)
print('dimensi setelah oversampling')
print('X_resampled\n', X_resampled.shape)
print('y_resampled\n', y_resampled.shape)

dimensi setelah oversampling
X_resampled
 (21, 7)
y_resampled
 (21,)

In [27]:
# lihat hasil setelah oversampling
out = pd.DataFrame({'x_resampled':y_resampled})
out['x_resampled'].value_counts()

Ganti lahar dinamo                             3
Ganti arang starter                            3
Ganti switch starter kemudian arang starter    3
Ganti switch starter                           3
Ganti aki                                      3
Tidak ada yang diganti                         3
Ganti dinamo starter                           3
Name: x_resampled, dtype: int64

Trlihat bahwa jumlah setiap class yang tersebar di kolom hasil memiliki jumlah yang sama yakni sebanyak 4. hal ini berarti variabel target telah memiliki class class yang balance

In [28]:
# REKONSTRUKSI ULANG DATA_1-Nya
data_1_rev = pd.DataFrame(X_resampled)
data_1_rev['hasil'] = y_resampled
data_1_rev.head()

    0  1        2      3      4        5      6                   hasil
0  12  3  <1tahun  Bagus  Tebal    Bagus  Bagus  Tidak ada yang diganti
1  12  3  <1tahun  Bagus  Tebal    Bagus  Rusak    Ganti dinamo starter
2  12  3  <1tahun  Bagus  Tebal  Meleleh  Bagus      Ganti lahar dinamo
3  12  3  <1tahun  Bagus  Tipis    Bagus  Bagus     Ganti arang starter
4  12  3  <1tahun  Rusak  Tebal    Bagus  Bagus    Ganti switch starter

#### perbaiki nama kolomnya

In [29]:
list_nama_kolom = data_4.columns # out ==> ['Gas', 'Slongsong Gas', 'Tali Gas', 'Oli', 'Hasil']
data_1_rev.columns = list_nama_kolom
data_1_rev

,Voltase,Arus,Umur,Switch,Arang,Lahar,Dinamo,Hasil
0,12,3,<1tahun,Bagus,Tebal,Bagus,Bagus,Tidak ada yang diganti
1,12,3,<1tahun,Bagus,Tebal,Bagus,Rusak,Ganti dinamo starter
2,12,3,<1tahun,Bagus,Tebal,Meleleh,Bagus,Ganti lahar dinamo
3,12,3,<1tahun,Bagus,Tipis,Bagus,Bagus,Ganti arang starter
4,12,3,<1tahun,Rusak,Tebal,Bagus,Bagus,Ganti switch starter
5,12,3,>1tahun,Bagus,Tebal,Bagus,Bagus,Ganti aki
6,12,<3,<1tahun,Bagus,Tebal,Bagus,Bagus,Ganti aki
7,<12,3,<1tahun,Bagus,Tebal,Bagus,Bagus,Ganti aki
8,12,3,>1tahun,Bagus,Tebal,Bagus,Bagus,Tidak ada yang diganti
9,12,3,<1tahun,Rusak,Tipis,Bagus,Bagus,Ganti switch starter kemudian arang starter
10,12,3,<1tahun,Bagus,Tipis,Bagus,Bagus,Ganti arang starter
11,12,3,<1tahun,Bagus,Tipis,Bagus,Bagus,Ganti arang starter
12,12,3,<1tahun,Bagus,Tebal,Bagus,Rusak,Ganti dinamo starter
13,12,3,<1tahun,Bagus,Tebal,Bagus,Rusak,Ganti dinamo starter
14,12,3,<1tahun,Bagus,Tebal,Meleleh,Bagus,Ganti lahar dinamo
15,12,3,<1tahun,Bagus,Tebal,Meleleh,Bagus,Ganti lahar dinamo
16,12,3,<1tahun,Rusak,Tebal,Bagus,Bagus,Ganti switch starter
17,12,3,<1tahun,Rusak,Tebal,Bagus,Bagus,Ganti switch starter
18,12,3,<1tahun,Rusak,Tipis,Bagus,Bagus,Ganti switch starter kemudian arang starter
19,12,3,<1tahun,Rusak,Tipis,Bagus,Bagus,Ganti switch starter kemudian arang starter
20,12,3,<1tahun,Bagus,Tebal,Bagus,Bagus,Tidak ada yang diganti

### Data Encoding (Transformation)

In [30]:
from sklearn import preprocessing
trans = preprocessing.LabelEncoder()
columns = data_1_rev.columns
data_encoded_storage = {}
labels_storage = {} # ini untuk meta data
for col in columns:
    out = trans.fit_transform(data_1_rev[col])
    out_lbl = trans.classes_
    labels_storage.update({col:out_lbl})
    data_encoded_storage.update({col:out})

### Rekonstruksi kembali dataset data_1_rev-nya ke dalam dataframe

In [31]:
data_1_rev = pd.DataFrame(data_encoded_storage)
data_1_rev.head() # lihat cuman 5 record data saja

   Voltase  Arus  Umur  Switch  Arang  Lahar  Dinamo  Hasil
0        0     0     0       0      0      0       0      6
1        0     0     0       0      0      0       1      2
2        0     0     0       0      0      1       0      3
3        0     0     0       0      1      0       0      1
4        0     0     0       1      0      0       0      4

### Splitting datanya menjadi training dan testing

In [32]:
from sklearn import model_selection
FEATURES = data_1_rev.iloc[:, :-1]
TARGET = data_1_rev.iloc[:, -1]
x_train, x_test, y_train, y_test = model_selection.train_test_split(
    FEATURES, 
    TARGET, 
    test_size=0.2
)
# cek dimensi datanya 
print('x_train : ', x_train.shape)
print('y_train : ', y_train.shape)
print('x_test  : ',  x_test.shape)
print('y_test  : ',  y_test.shape)

x_train :  (16, 7)
y_train :  (16,)
x_test  :  (5, 7)
y_test  :  (5,)

In [33]:
# import library algoritma pelatihannya
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.neural_network import MLPClassifier

# import library untuk mengukur akurasi dan laporan hasil klasifikasi
from sklearn.metrics import accuracy_score, classification_report

# inisialisasi model-nya
models = {
    "Support_vector_machine": SVC(kernel="linear", gamma="auto"),
    "Decission_Tree": DecisionTreeClassifier(criterion='entropy'),
    "multi_layer_perceptron": MLPClassifier(hidden_layer_sizes=(250),max_iter=1000,batch_size=100)
}

# membuat fungsi untuk melakukan fungsi fitting atau training
def train_model (model,xtrain,ytrain):
    model.fit(xtrain,ytrain)

# membuat fungsi untuk menampilkan akurasi dan classifiation_report
def predict(i,model,xtest,ytest):
    pred = model.predict(xtest)
    accuracy = accuracy_score(ytest, pred) * 100
    print("\n",i,":")
    print(classification_report(ytest, pred))
    print("accuracy : \n", round(accuracy,3),"%\n")

# melakukan training dengan menggunakan semua algoritma yang telah diinisialisasi
for i in models:
    train_model(models[i],x_train,y_train)
    predict(i,models[i],x_test,y_test)

 Support_vector_machine :
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       1.00      1.00      1.00         1
           2       1.00      1.00      1.00         1
           3       1.00      1.00      1.00         1
           6       0.50      1.00      0.67         1

   micro avg       0.80      0.80      0.80         5
   macro avg       0.70      0.80      0.73         5
weighted avg       0.70      0.80      0.73         5

accuracy :
 80.0 %


 Decission_Tree :
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       1.00      1.00      1.00         1
           2       1.00      1.00      1.00         1
           3       1.00      1.00      1.00         1
           6       0.50      1.00      0.67         1

   micro avg       0.80      0.80      0.80         5
   macro avg       0.70      0.80      0.73         5
weighted avg       0.70      0.80      0.73         5

accuracy :
 80.0 %


 multi_layer_perceptron :
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       1.00      1.00      1.00         1
           2       1.00      1.00      1.00         1
           3       1.00      1.00      1.00         1
           6       0.50      1.00      0.67         1

   micro avg       0.80      0.80      0.80         5
   macro avg       0.70      0.80      0.73         5
weighted avg       0.70      0.80      0.73         5

accuracy :
 80.0 %

In [34]:
labels_storage.get('Hasil')

array(['Ganti aki', 'Ganti arang starter', 'Ganti dinamo starter',
       'Ganti lahar dinamo', 'Ganti switch starter',
       'Ganti switch starter kemudian arang starter',
       'Tidak ada yang diganti'], dtype=object)

In [35]:
# kita siimpan model yang sudah dihasilkan ke format pickle (.pkl)
# import library pickle-nya
import pickle
import os 

# ambil models nya
data_no = 4
folder_name = 'model_{}'.format(data_no)

if os.path.exists(folder_name):
    print('path exist')
else:
    os.mkdir(folder_name)

model_mlp = models['multi_layer_perceptron']

# simpan file model yang sudah dilatih ke dalam format pickle
model_name = '{}/model_data_{}.pkl'.format(folder_name, data_no)
pickle.dump(model_mlp, open(model_name, 'wb'))

# simpan variabel class_keputusan ke dalam format pickle
label_name = '{}/label_data_{}.pkl'.format(folder_name, data_no)
pickle.dump(labels_storage, open(label_name, 'wb'))

print('Done')

Done