In [31]:
import numpy as np 
import pandas as pd 
import sklearn
import warnings

In [32]:
def warn(*args, **kwargs):
    pass 
warnings.warn = warn

In [33]:
# file csv yang akan diproses
file_4 = 'starter.csv'

# panggil filenya dan masukan ke dalam variabel data_n
data_4 = pd.read_csv(file_4)

# lihat dimensi semua filenya 
print('(n_baris, n_kolom)')
print('data_2 :\n', data_4.shape)

(n_baris, n_kolom)
data_2 :
 (20, 8)

### DATA_1

In [34]:
# lihat unique setiap kolom 
for col in data_4.columns:
    out = data_4[col].unique()
    print(col, ' :\n', out)

Voltase  :
 ['12' '<12']
Arus  :
 ['3' '<3']
Umur  :
 ['<1tahun' '>1tahun' '>2tahun']
Switch  :
 ['Bagus' 'Rusak']
Arang  :
 ['Tebal' 'Tipis' 'Sedang']
Lahar  :
 ['Bagus' 'Meleleh' 'Belum meleleh']
Dinamo  :
 ['Bagus' 'Rusak']
Hasil  :
 ['Kondisi baik' 'Kondisi rusak']

In [35]:
# kita lihat nilai - nilai unique dalam datanya
data_4['Hasil'].unique()

array(['Kondisi baik', 'Kondisi rusak'], dtype=object)

In [36]:
# kita hitung berapa jumlah kelas di kolom 'Hasil' tersbeut 
data_4['Hasil'].value_counts()

Kondisi rusak    13
Kondisi baik      7
Name: Hasil, dtype: int64

Terlihat bahwa jumlah class yang tersebar di dalam kolom Hasil itu bersifat tidak merata. artinya class 'Tidak ada yang diganti' memiliki jumlah paling banyak (mendominasi) dibandingkan dengan class yang lain seperti 'Oli diganti', 'tali gas diganti' dll. sehingga, agar menghasilkan model yang baik, maka jumlah class ini harus disama-ratakan (balancing) agar distribusi nilainya merata. sehingga akan semakin baik dalam menyimpulkan/memprediksi data

### Random oversampling

In [37]:
'''
import library imblearn. karena data kita mengalami imbalance class
di mana imbalance class ini merupakan kondisi ketidakseimabagan jumlah 
class yang terdistribusi di dalam suatu field/kolom, sehingga menyebabkan
sistem tersebut mengalami kesulitasn dalam training dan validasi.
'''
from imblearn.over_sampling import RandomOverSampler
from collections import Counter

# kita pecah datasetnya menjadi dua bagian yaitu variabel features dan variabel target
# X ==> berisi variabel-variabel features
X = data_4.iloc[:, :-1]

# Y ==> berisi sebuah variabel target
y = data_4.iloc[:, -1]

# mulai sampling
ros = RandomOverSampler(random_state=0, )
X_resampled, y_resampled = ros.fit_sample(X, y)
print('dimensi setelah oversampling')
print('X_resampled\n', X_resampled.shape)
print('y_resampled\n', y_resampled.shape)

dimensi setelah oversampling
X_resampled
 (26, 7)
y_resampled
 (26,)

In [38]:
# lihat hasil setelah oversampling
out = pd.DataFrame({'x_resampled':y_resampled})
out['x_resampled'].value_counts()

Kondisi baik     13
Kondisi rusak    13
Name: x_resampled, dtype: int64

Trlihat bahwa jumlah setiap class yang tersebar di kolom hasil memiliki jumlah yang sama yakni sebanyak 4. hal ini berarti variabel target telah memiliki class class yang balance

In [39]:
# REKONSTRUKSI ULANG DATA_1-Nya
data_1_rev = pd.DataFrame(X_resampled)
data_1_rev['hasil'] = y_resampled
data_1_rev.head()

    0  1        2      3      4        5      6          hasil
0  12  3  <1tahun  Bagus  Tebal    Bagus  Bagus   Kondisi baik
1  12  3  <1tahun  Bagus  Tebal    Bagus  Rusak  Kondisi rusak
2  12  3  <1tahun  Bagus  Tebal  Meleleh  Bagus  Kondisi rusak
3  12  3  <1tahun  Bagus  Tipis    Bagus  Bagus  Kondisi rusak
4  12  3  <1tahun  Rusak  Tebal    Bagus  Bagus  Kondisi rusak

#### perbaiki nama kolomnya

In [40]:
list_nama_kolom = data_4.columns # out ==> ['Gas', 'Slongsong Gas', 'Tali Gas', 'Oli', 'Hasil']
data_1_rev.columns = list_nama_kolom
data_1_rev

   Voltase Arus     Umur Switch   Arang          Lahar Dinamo          Hasil
0       12    3  <1tahun  Bagus   Tebal          Bagus  Bagus   Kondisi baik
1       12    3  <1tahun  Bagus   Tebal          Bagus  Rusak  Kondisi rusak
2       12    3  <1tahun  Bagus   Tebal        Meleleh  Bagus  Kondisi rusak
3       12    3  <1tahun  Bagus   Tipis          Bagus  Bagus  Kondisi rusak
4       12    3  <1tahun  Rusak   Tebal          Bagus  Bagus  Kondisi rusak
5       12    3  >1tahun  Bagus   Tebal          Bagus  Bagus  Kondisi rusak
6       12   <3  <1tahun  Bagus   Tebal          Bagus  Bagus  Kondisi rusak
7      <12    3  <1tahun  Bagus   Tebal          Bagus  Bagus  Kondisi rusak
8       12    3  >1tahun  Bagus   Tebal          Bagus  Bagus  Kondisi rusak
9       12    3  <1tahun  Rusak   Tipis          Bagus  Bagus  Kondisi rusak
10     <12   <3  <1tahun  Bagus   Tebal          Bagus  Bagus  Kondisi rusak
11      12    3  >1tahun  Bagus   Tebal          Bagus  Bagus   Kondisi baik
12      12    3  >2tahun  Bagus   Tebal          Bagus  Bagus   Kondisi baik
13     <12    3  >2tahun  Bagus   Tebal          Bagus  Bagus  Kondisi rusak
14      12    3  <1tahun  Bagus  Sedang          Bagus  Bagus   Kondisi baik
15      12    3  <1tahun  Bagus  Sedang  Belum meleleh  Bagus   Kondisi baik
16      12    3  <1tahun  Bagus  Sedang  Belum meleleh  Bagus   Kondisi baik
17      12    3  <1tahun  Rusak  Sedang          Bagus  Bagus  Kondisi rusak
18      12    3  >1tahun  Bagus  Sedang          Bagus  Bagus   Kondisi baik
19     <12    3  >1tahun  Bagus  Sedang  Belum meleleh  Bagus  Kondisi rusak
20      12    3  <1tahun  Bagus  Sedang  Belum meleleh  Bagus   Kondisi baik
21      12    3  <1tahun  Bagus  Sedang  Belum meleleh  Bagus   Kondisi baik
22      12    3  <1tahun  Bagus   Tebal          Bagus  Bagus   Kondisi baik
23      12    3  <1tahun  Bagus  Sedang          Bagus  Bagus   Kondisi baik
24      12    3  <1tahun  Bagus  Sedang          Bagus  Bagus   Kondisi baik
25      12    3  <1tahun  Bagus  Sedang          Bagus  Bagus   Kondisi baik

### Data Encoding (Transformation)

In [41]:
from sklearn import preprocessing
trans = preprocessing.LabelEncoder()
columns = data_1_rev.columns
data_encoded_storage = {}
labels_storage = {} # ini untuk meta data
for col in columns:
    out = trans.fit_transform(data_1_rev[col])
    out_lbl = trans.classes_
    labels_storage.update({col:out_lbl})
    data_encoded_storage.update({col:out})

### Rekonstruksi kembali dataset data_1_rev-nya ke dalam dataframe

In [42]:
data_1_rev = pd.DataFrame(data_encoded_storage)
data_1_rev.head() # lihat cuman 5 record data saja

   Voltase  Arus  Umur  Switch  Arang  Lahar  Dinamo  Hasil
0        0     0     0       0      1      0       0      0
1        0     0     0       0      1      0       1      1
2        0     0     0       0      1      2       0      1
3        0     0     0       0      2      0       0      1
4        0     0     0       1      1      0       0      1

### Splitting datanya menjadi training dan testing

In [43]:
from sklearn import model_selection
FEATURES = data_1_rev.iloc[:, :-1]
TARGET = data_1_rev.iloc[:, -1]
x_train, x_test, y_train, y_test = model_selection.train_test_split(
    FEATURES, 
    TARGET, 
    test_size=0.2
)
# cek dimensi datanya 
print('x_train : ', x_train.shape)
print('y_train : ', y_train.shape)
print('x_test  : ',  x_test.shape)
print('y_test  : ',  y_test.shape)

x_train :  (20, 7)
y_train :  (20,)
x_test  :  (6, 7)
y_test  :  (6,)

In [44]:
# import library algoritma pelatihannya
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.neural_network import MLPClassifier

# import library untuk mengukur akurasi dan laporan hasil klasifikasi
from sklearn.metrics import accuracy_score, classification_report

# inisialisasi model-nya
models = {
    "Support_vector_machine": SVC(kernel="linear", gamma="auto"),
    "Decission_Tree": DecisionTreeClassifier(criterion='entropy'),
    "multi_layer_perceptron": MLPClassifier(hidden_layer_sizes=(250),max_iter=1000,batch_size=100)
}

# membuat fungsi untuk melakukan fungsi fitting atau training
def train_model (model,xtrain,ytrain):
    model.fit(xtrain,ytrain)

# membuat fungsi untuk menampilkan akurasi dan classifiation_report
def predict(i,model,xtest,ytest):
    pred = model.predict(xtest)
    accuracy = accuracy_score(ytest, pred) * 100
    print("\n",i,":")
    print(classification_report(ytest, pred))
    print("accuracy : \n", round(accuracy,3),"%\n")

# melakukan training dengan menggunakan semua algoritma yang telah diinisialisasi
for i in models:
    train_model(models[i],x_train,y_train)
    predict(i,models[i],x_test,y_test)

 Support_vector_machine :
              precision    recall  f1-score   support

           0       1.00      0.67      0.80         3
           1       0.75      1.00      0.86         3

   micro avg       0.83      0.83      0.83         6
   macro avg       0.88      0.83      0.83         6
weighted avg       0.88      0.83      0.83         6

accuracy :
 83.333 %


 Decission_Tree :
              precision    recall  f1-score   support

           0       0.67      0.67      0.67         3
           1       0.67      0.67      0.67         3

   micro avg       0.67      0.67      0.67         6
   macro avg       0.67      0.67      0.67         6
weighted avg       0.67      0.67      0.67         6

accuracy :
 66.667 %


 multi_layer_perceptron :
              precision    recall  f1-score   support

           0       0.67      0.67      0.67         3
           1       0.67      0.67      0.67         3

   micro avg       0.67      0.67      0.67         6
   macro avg       0.67      0.67      0.67         6
weighted avg       0.67      0.67      0.67         6

accuracy :
 66.667 %

In [45]:
labels_storage.get('Hasil')

array(['Kondisi baik', 'Kondisi rusak'], dtype=object)

In [46]:
# kita siimpan model yang sudah dihasilkan ke format pickle (.pkl)
# import library pickle-nya
import pickle
import os 

# ambil models nya
data_no = 4
folder_name = 'model_{}'.format(data_no)

if os.path.exists(folder_name):
    print('path exist')
else:
    os.mkdir(folder_name)

model_mlp = models['multi_layer_perceptron']

# simpan file model yang sudah dilatih ke dalam format pickle
model_name = '{}/model_data_{}.pkl'.format(folder_name, data_no)
pickle.dump(model_mlp, open(model_name, 'wb'))

# simpan variabel class_keputusan ke dalam format pickle
label_name = '{}/label_data_{}.pkl'.format(folder_name, data_no)
pickle.dump(labels_storage, open(label_name, 'wb'))

print('Done')

path exist
Done